In [22]:
import numpy as np

In [88]:
  np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
y = np.arange(10)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [103]:
np.array([1, 3,5])

array([1, 3, 5])

In [155]:
y=np.array([[1, 3,5],[2, 6, 8]])
print(y)
type(y)

[[1 3 5]
 [2 6 8]]


numpy.ndarray

In [108]:
y.shape

(2, 3)

In [109]:
y.dtype

dtype('int64')

In [167]:
np.array((2,7))

array([2, 7])

In [149]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [151]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [152]:
np.empty(8)

array([0.00000000e+000, 2.58883488e-312, 2.41907520e-312, 2.44029516e-312,
       1.20953760e-312, 2.05833592e-312, 8.70018274e-313, 0.00000000e+000])

In [154]:
np.empty((4,3))

array([[0.00000000e+000, 7.41098469e-323, 0.00000000e+000],
       [0.00000000e+000, 1.93101617e-312, 2.46567317e+179],
       [4.96828963e-091, 1.16065909e-046, 3.63372993e+174],
       [8.84885163e+165, 3.99910963e+252, 6.80124890e-310]])

In [156]:
y*y

array([[ 1,  9, 25],
       [ 4, 36, 64]])

In [157]:
y+y

array([[ 2,  6, 10],
       [ 4, 12, 16]])

In [158]:
y

array([[1, 3, 5],
       [2, 6, 8]])

In [159]:
y-y

array([[0, 0, 0],
       [0, 0, 0]])

In [160]:
y/y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [161]:
1/y

array([[1.        , 0.33333333, 0.2       ],
       [0.5       , 0.16666667, 0.125     ]])

In [162]:
1/y

array([[1.        , 0.33333333, 0.2       ],
       [0.5       , 0.16666667, 0.125     ]])

In [163]:
print(1/y)

[[1.         0.33333333 0.2       ]
 [0.5        0.16666667 0.125     ]]


# Slicing of numpy

In [164]:
y.shape

(2, 3)

In [168]:
l=[1,2,4]

In [169]:
l

[1, 2, 4]

In [170]:
l[0:2]

[1, 2]

In [171]:
l2=l[0:2]

In [172]:
l2

[1, 2]

In [173]:
l2[0]=9

In [174]:
l2

[9, 2]

In [175]:
l

[1, 2, 4]

In [202]:
l=np.array([1,2,3, 7,9])

In [203]:
l

array([1, 2, 3, 7, 9])

In [204]:
l1=l[0:3].copy()

In [205]:
l1

array([1, 2, 3])

In [206]:
l1[2]=4

In [207]:
l1

array([1, 2, 4])

In [208]:
l

array([1, 2, 3, 7, 9])

In [209]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [210]:
y=np.arange(10)

In [211]:
y[0]

0

In [212]:
y[1]

1

In [213]:
y[2]

2

In [215]:
np.array([2,5,7])

array([2, 5, 7])

In [216]:
e=np.array([2,5,7])

In [217]:
e[0]

2

In [218]:
e[1]

5

# Numpy function

In [226]:
y =np.array([4,5])

In [227]:
y[0]

4

In [229]:
y[0:2]

array([4, 5])

In [238]:
y=np.array([[1,5,6],[9, 6, 8]])
print(y)
type(y)

[[1 5 6]
 [9 6 8]]


numpy.ndarray

In [241]:
y.sort()

In [242]:
y

array([[1, 5, 6],
       [6, 8, 9]])

In [246]:
y=np.array([[1,5,6],[9, 6, 8]])
y.sum(axis=0)


array([10, 11, 14])

In [247]:
y.sum(axis=1)

array([12, 23])

In [248]:
y

array([[1, 5, 6],
       [9, 6, 8]])

In [249]:
y[0:3]

array([[1, 5, 6],
       [9, 6, 8]])

In [253]:
t=y([2, 3])

TypeError: 'numpy.ndarray' object is not callable

In [292]:
t

array([[1, 5, 6],
       [9, 6, 8]])

In [293]:
y=np.array({1,5,6})

In [294]:
y

array({1, 5, 6}, dtype=object)

In [295]:
y= np.array([1,2,3,4])

In [296]:
np.arange(0,4)

array([0, 1, 2, 3])

In [297]:
y[0:3]

array([1, 2, 3])

In [298]:
y.shape

(4,)

In [299]:
t.shapoe

AttributeError: 'numpy.ndarray' object has no attribute 'shapoe'

In [313]:
t.shape


(2, 3)

In [309]:
c= t.reshape(3,2)

In [322]:
print(c)

[[1 5]
 [6 9]
 [6 8]]


In [323]:
c.ravel()

array([1, 5, 6, 9, 6, 8])

In [314]:
d=([1,4,5],[1,9,5],[6,7,8])

In [399]:
array1=np.array(d)

In [316]:
array1

array([[1, 4, 5],
       [1, 9, 5],
       [6, 7, 8]])

In [317]:
array1.sum(axis=0)

array([ 8, 20, 18])

In [319]:
array1.shape

(3, 3)

In [320]:
array1.sum(axis=1)

array([10, 15, 21])

In [365]:
array1.T

array([[1, 1, 6],
       [4, 9, 7],
       [5, 5, 8]])

In [326]:
v= np.array([[2,3,5],[4,7,8]])

In [375]:
v.ravel()

array([2, 3, 5, 4, 7, 8])

In [377]:
c= v.flat
print(c)

In [378]:
for x in c:
    print(x)

2
3
5
4
7
8


In [388]:
v.ndim

2

In [389]:
v.size

6

In [392]:
array1.sort()

In [411]:
array1

array([[1, 4, 5],
       [1, 9, 5],
       [6, 7, 8]])

In [412]:
np.sqrt(array1)

array([[1.        , 2.        , 2.23606798],
       [1.        , 3.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [413]:
y=[1,4,7]

In [414]:
y=np.array(y)

In [415]:
np.sqrt(y)

array([1.        , 2.        , 2.64575131])

In [416]:
np.sum(y)

12

In [417]:
np.sum(array1)

46

In [418]:
array1.sum()

46

In [422]:
array2=[1,3,5],[2,5,6]

In [423]:
np.sum(array2)

22

In [424]:
array2.sum()

AttributeError: 'tuple' object has no attribute 'sum'

In [425]:
array2=np.array(array2)

In [426]:
array2.sum()

22

In [427]:
array2.min()

1

In [429]:
array2.max()

6